version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      # DB_USERNAME, DB_PASSWORD, ADMIN_PASSWORD - передаются при запуске!
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=language
      # POSTGRES_USER, POSTGRES_PASSWORD - передаются при запуске!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: